version: 2
jobs:
  build-node-6:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run: yarn
      - run: yarn run pretest
      - run: yarn run test-ci
      - run: yarn run posttest
  build-node-8:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: yarn
      - run: yarn run pretest
      - run: yarn run test-ci
      - run: yarn run posttest
  build-node-10:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: yarn
      - run: yarn run pretest
      - run: yarn run test-ci
      - run: yarn run posttest
workflows:
  version: 2
  build:
    jobs:
      - build-node-6
      - build-node-8
      - build-node-10
