version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - run: npm run pretest
      - run: npm run test-ci
      - run: npm run posttest
