name: Node CI

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [6.x, 8.x, 10.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install, build, and test
      run: |
        yarn
        yarn run test
  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          node-version: 8.x
      - name: Check for eslint
        run: |
          yarn run lint
  bundlesize:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          node-version: 8.x
      - name: Check for assets size
        run: |
          yarn run bundlesize
