name: Melody CI

on:
  pull_request:
  push:
    branches-ignore:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [6.x, 8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
  
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: yarn install and build
      run: yarn

    - name: lint
      run: yarn run lint

    - name: test
      run: yarn run test

    - name: bundlesize
      run: yarn run bundlesize
      
